### ISSUE TITLE
first installation error : unable to download c302 module

### ISSUE THREAD

**Issue by woobin3069** [openworm/c302#32]
Hello, 
I tried to use sibernetic_c302.py to simulate C. eleganse,
but error occurred.

```
Collecting c302
  Using cached c302-0.7.0.tar.gz (35.1 MB)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from c302) (1.19.4)
Requirement already satisfied: xlrd in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from c302) (2.0.1)
Collecting xlwt
  Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Requirement already satisfied: libNeuroML>=0.2.39 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from c302) (0.2.53)
Requirement already satisfied: pyNeuroML>=0.3.11 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from c302) (0.5.5)
Collecting pyopenworm==0.7.1
  Using cached PyOpenWorm-0.7.1.tar.gz (339 kB)
Requirement already satisfied: lxml in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from libNeuroML>=0.2.39->c302) (4.6.2)
Requirement already satisfied: six in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from libNeuroML>=0.2.39->c302) (1.15.0)
Requirement already satisfied: argparse in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyNeuroML>=0.3.11->c302) (1.4.0)
Requirement already satisfied: pylems>=0.4.9.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyNeuroML>=0.3.11->c302) (0.5.1)
Requirement already satisfied: airspeed==0.5.4dev-20150515 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyNeuroML>=0.3.11->c302) (0.5.4.dev20150515)
Requirement already satisfied: neuromllite>=0.1.9 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyNeuroML>=0.3.11->c302) (0.1.9)
Requirement already satisfied: kiwisolver<=1.1.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyNeuroML>=0.3.11->c302) (1.1.0)
Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyNeuroML>=0.3.11->c302) (3.3.3)
Collecting bibtexparser==0.6.1
  Using cached bibtexparser-0.6.1.tar.gz (26 kB)
Collecting BTrees==4.0.8
  Using cached BTrees-4.0.8.tar.gz (608 kB)

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pycharm-packaging\\btrees\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pycharm-packaging\\btrees\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-kckznqqe'
         cwd: C:\Users\USER\AppData\Local\Temp\pycharm-packaging\btrees\
    Complete output (46 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-wheel-rczjvzy3\\persistent\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-wheel-rczjvzy3\\persistent\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USER\AppData\Local\Temp\pip-wheel-h6lc6nk8'
           cwd: C:\Users\USER\AppData\Local\Temp\pip-wheel-rczjvzy3\persistent\
      Complete output (8 lines):
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for persistent
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmpuvxibmva', '--quiet', 'persistent']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pycharm-packaging\btrees\setup.py", line 116, in <module>
        setup(name='BTrees',
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
        return installer(requirement)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmpuvxibmva', '--quiet', 'persistent']' returned non-zero exit status 1.
```

I thought it's maybe the problem of the latest version, 
so I tried to download 0.6.0 version of c302

```
Collecting c302==0.6.0
  Using cached c302-0.6.0.tar.gz (642 kB)

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pycharm-packaging\\c302\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pycharm-packaging\\c302\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-evn57mh0'
         cwd: C:\Users\USER\AppData\Local\Temp\pycharm-packaging\c302\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pycharm-packaging\c302\setup.py", line 6, in <module>
        import c302
      File "C:\Users\USER\AppData\Local\Temp\pycharm-packaging\c302\c302\__init__.py", line 1416
        print 555522
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(555522)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
```

But an even weirder error occurred.
Please help...

**Comment by pgleeson** [comment]
@woobin3069 The specific error above is due to a non python 3 compatible line in v0.6.0 of c302, which is quite old. 
The latest version of c302 should work well with sibernetic, you can see instructions on installing that here: https://github.com/openworm/c302#to-install--test

Note: a specific version of owmeta (previously known as PyOpenWorm) is required for c302. It's not absolutely required, but you'll get lots of warnings if it's not found. See here: https://github.com/openworm/OpenWorm/blob/master/Dockerfile3#L111 for the precise versions of c302/sibernetic/PyOpenWorm required for the full software stack in Python3, which can either be built with Docker, or copied for manual local install. 

I'll hopefully sort out a new release of c302 which works better out of the box with all of these early in the new year.

**Comment by woobin3069** [comment]
@pgleeson Thank you for your attention to this matter.
Thanks to you, now I can do many things with OpenWorm project.
Once again, thank you.

**Comment by pgleeson** [comment]
Thanks again for your interest in OpenWorm @woobin3069
